POST http://localhost:8776/api/register
Content-Type: application/json

{
    "name":"jhon21",
    "email":"admin21@gmail.com",
    "password":"password",
    "password_confirmation":"password"
}
###

POST http://localhost:8776/api/login
Content-Type: application/json

{
    "email" : "admin21@gmail.com",
    "password" : "password"
}

###
GET http://localhost:8776/api/userdata
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjk0MDA5NjExLCJleHAiOjE2OTQwMTMyMTEsIm5iZiI6MTY5NDAwOTYxMSwianRpIjoiN01XdVNKZXFDVWlWc2xZbCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.natqoPB6fN4dX_IExiUoyNXLEpJrPIV8tl-wGR0u_ks

###
GET http://localhost:8776/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjk0MDA5NjExLCJleHAiOjE2OTQwMTMyMTEsIm5iZiI6MTY5NDAwOTYxMSwianRpIjoiN01XdVNKZXFDVWlWc2xZbCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.natqoPB6fN4dX_IExiUoyNXLEpJrPIV8tl-wGR0u_ks

###
GET http://localhost:8776/api/post
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjk0MDA5NjExLCJleHAiOjE2OTQwMTMyMTEsIm5iZiI6MTY5NDAwOTYxMSwianRpIjoiN01XdVNKZXFDVWlWc2xZbCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.natqoPB6fN4dX_IExiUoyNXLEpJrPIV8tl-wGR0u_ks

###
POST http://localhost:8776/api/post/store
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjk0MDA5NjExLCJleHAiOjE2OTQwMTMyMTEsIm5iZiI6MTY5NDAwOTYxMSwianRpIjoiN01XdVNKZXFDVWlWc2xZbCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.natqoPB6fN4dX_IExiUoyNXLEpJrPIV8tl-wGR0u_ks

{
    "image":"",
    "title":"tess",
    "content":"tess"
}

###
POST http://localhost:8776/api/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjk0MDA5NjExLCJleHAiOjE2OTQwMTMyMTEsIm5iZiI6MTY5NDAwOTYxMSwianRpIjoiN01XdVNKZXFDVWlWc2xZbCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.natqoPB6fN4dX_IExiUoyNXLEpJrPIV8tl-wGR0u_ks

###
POST http://localhost:8776/api/post/store
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjk0MDA5NjExLCJleHAiOjE2OTQwMTMyMTEsIm5iZiI6MTY5NDAwOTYxMSwianRpIjoiN01XdVNKZXFDVWlWc2xZbCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.natqoPB6fN4dX_IExiUoyNXLEpJrPIV8tl-wGR0u_ks

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

tess
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

tess
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

@./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://localhost:8776/api/post/store
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjk0MDA5NjExLCJleHAiOjE2OTQwMTMyMTEsIm5iZiI6MTY5NDAwOTYxMSwianRpIjoiN01XdVNKZXFDVWlWc2xZbCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.natqoPB6fN4dX_IExiUoyNXLEpJrPIV8tl-wGR0u_ks
Accept: application/json

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

tess
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

tess
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="aa.png"
Content-Type: image/png

@C:\Users\acer\OneDrive\Pictures\Screenshot\aa.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
