POST http://localhost:8776/api/register
Content-Type: application/json

{
    "name":"jhon21",
    "email":"admin21@gmail.com",
    "password":"password",
    "password_confirmation":"password"
}
###

POST http://localhost:8776/api/login
Content-Type: application/json

{
    "email" : "admin2@gmail.com",
    "password" : "password"
}

###
GET http://localhost:8776/api/userdata
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjkzOTkwMjA4LCJleHAiOjE2OTM5OTM4MDgsIm5iZiI6MTY5Mzk5MDIwOCwianRpIjoiMWJFaWNKMXB3bGlENHlQQyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.RUgzkLY2Q6G1UoYW2ILns5wiuD0Y970LA82oKSQv-R8

###
GET http://localhost:8776/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjkzOTkwMjA4LCJleHAiOjE2OTM5OTM4MDgsIm5iZiI6MTY5Mzk5MDIwOCwianRpIjoiMWJFaWNKMXB3bGlENHlQQyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.RUgzkLY2Q6G1UoYW2ILns5wiuD0Y970LA82oKSQv-R8

###
GET http://localhost:8776/api/post
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjkzOTkwMjA4LCJleHAiOjE2OTM5OTM4MDgsIm5iZiI6MTY5Mzk5MDIwOCwianRpIjoiMWJFaWNKMXB3bGlENHlQQyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.RUgzkLY2Q6G1UoYW2ILns5wiuD0Y970LA82oKSQv-R8

###
POST http://localhost:8776/api/post/store
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjkzOTkwMjA4LCJleHAiOjE2OTM5OTM4MDgsIm5iZiI6MTY5Mzk5MDIwOCwianRpIjoiMWJFaWNKMXB3bGlENHlQQyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.RUgzkLY2Q6G1UoYW2ILns5wiuD0Y970LA82oKSQv-R8

{
    "image":"",
    "title":"tess",
    "content":"tess"
}

###
POST http://localhost:8776/api/post/store
Content-Type: multipart/form-data
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg3NzYvYXBpL2xvZ2luIiwiaWF0IjoxNjkzOTkwMjA4LCJleHAiOjE2OTM5OTM4MDgsIm5iZiI6MTY5Mzk5MDIwOCwianRpIjoiMWJFaWNKMXB3bGlENHlQQyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.RUgzkLY2Q6G1UoYW2ILns5wiuD0Y970LA82oKSQv-R8

--boundary
Content-Disposition: form-data; name="image"; filename="gambar.jpg"
Content-Type: image/jpeg

[Binary file content here]
--boundary
Content-Disposition: form-data; name="title"

tess
--boundary
Content-Disposition: form-data; name="content"

tess
--boundary--